In [7]:
import numpy as np

### CNN PARAMS
from param_all4_2D_smallFilter_1batchNorm_multiSlice_dataGenerator import * 

import lightcone_functions

%load_ext autoreload
%autoreload 2
#%reload_ext autoreload

In [4]:
import h5py

In [5]:
### TRAINING
DATA_DIR = '/media/yqin/81614149-2ed8-4c76-82e1-c46763d086fa/ngillet/LC_SLICE10_px100_2200_N10000_randICs_train.hdf5'

In [9]:
with h5py.File(DATA_DIR, 'r', swmr=True) as f:
    data = f['LC_train']
    t = np.array([1,3,4,6])
    print(data[ list(t) ].shape)
    sub_data = f['LC_train'][ [1,2,3,4,5] ]
    for key in f.keys():
        print(key)

(4, 100, 2200, 1)
LC_test
LC_train
LC_val
Param_raw_test
Param_raw_train
Param_raw_val
Param_test
Param_train
Param_val


In [47]:
array =  np.arange(100,110)
np.random.shuffle(array)
print(array)
ID_sorted_array = np.argsort( array )
print(ID_sorted_array)
sorted_array = array[ID_sorted_array]
print( sorted_array )

original_array = sorted_array[ np.argsort(ID_sorted_array) ]
print( original_array )

[102 109 105 104 107 101 108 103 106 100]
[9 5 0 7 3 2 8 4 6 1]
[100 101 102 103 104 105 106 107 108 109]
[102 109 105 104 107 101 108 103 106 100]


In [48]:
np.random.shuffle?

In [1]:
from keras import backend as K

print( K.tensorflow_backend._get_available_gpus() )
from tensorflow.python.client import device_lib
print( device_lib.list_local_devices() )

Using TensorFlow backend.


['/job:localhost/replica:0/task:0/device:GPU:0']
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 15973659526459358145
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 4271990629158352089
physical_device_desc: "device: XLA_CPU device"
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 3693506309512864922
physical_device_desc: "device: XLA_GPU device"
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 10823450624
locality {
  bus_id: 2
  numa_node: 1
  links {
  }
}
incarnation: 5801810668478178703
physical_device_desc: "device: 0, name: TITAN V, pci bus id: 0000:83:00.0, compute capability: 7.0"
]
